### ISSUE TITLE
First line of code is obscured in the editor 

### ISSUE THREAD

**Issue by alexgrejuc** [The-Code-In-Sheep-s-Clothing/Spiel-Front#10]
I see this on Firefox 74.0 and Chrome 79.0.3945.88 on Ubuntu 18.04.4. If it is not an issue on Mac and Windows then it's not worth fixing. 

![image](https://user-images.githubusercontent.com/6590681/78185164-80af4600-741f-11ea-9a7e-1d39d5a4aa0d.png)

![image](https://user-images.githubusercontent.com/6590681/78185188-8b69db00-741f-11ea-8e21-8003f886dcf9.png)

**Comment by montymxb** [comment]
I don't think this is an issue on mac right now, but it might still be worth checking out. I use firefox most of the time, so I'll need to check on chrome as well. It seems like a css issue, can be kind of weird to get it consistent across platforms...we'll keep an eye on it in the meantime.

**Comment by calgagi** [comment]
Don't get the issue on my computer currently. (Windows/Chrome)

**Comment by calgagi** [comment]
I did specifically run into this bug on my own machine recently though, and it should've been fixed with one of my commits in the terminal PR
