### ISSUE TITLE
Fix parse error display 

### ISSUE THREAD

**Issue by alexgrejuc** [The-Code-In-Sheep-s-Clothing/Spiel-Front#11]
Here is an example of a bad parse of the line `bad = 33`:

`SpielParseError: 37,5,game,"\"=\"\"=\"\"=\"\"=\"\":\""`

**Comment by calgagi** [comment]
If I have the line `bad = 33` in the editor and try to run it, it gives that as the error?

**Comment by alexgrejuc** [comment]
bad = 33 is probably not the best example, it requires some context. A better one would be something like 1 +. I have noticed that the behavior of parse/type errors differs in REPL expressions vs code written in the editor, but in both cases there should be a parse error.
