### ISSUE TITLE
either utilize electron taskbar or get rid of it

### ISSUE THREAD

**Issue by m0deran** [The-Code-In-Sheep-s-Clothing/Spiel-Front#15]
Electron has its own task bar. We can either use that instead of the nav-bar, or we should get rid of it. I'm in favor of using it: we can then have nice shortcuts and it will integrate with the user's OS nicely

**Comment by m0deran** [comment]
did some work on this in packaging branch. it works on macOS but there are windows and linux specific ways of doing this as well

**Comment by montymxb** [comment]
Closed as the online version of the tool does not have an electron taskbar.
