### ISSUE TITLE
make build process better

### ISSUE THREAD

**Issue by m0deran** [The-Code-In-Sheep-s-Clothing/Spiel-Front#17]
Integrate stack/npm together somehow, with a makefile or Nix. This should probably be done in the super-repo Spiel

**Comment by m0deran** [comment]
also the build process involves arcane rituals that I do not understand. can someone who is better at js/npm look at what I wrote?

**Comment by calgagi** [comment]
I will look tomorrow!

**Comment by montymxb** [comment]
Closed as the build process is `npm run build` 👍 , that's all that is needed to produce a static website.
