### ISSUE TITLE
Issues from 4/7 meeting

### ISSUE THREAD

**Issue by calgagi** [The-Code-In-Sheep-s-Clothing/Spiel-Front#19]
Change input mode character (>input) - Struggling to do
LOW: Get rid of load button or make it work properly - Done
Better error/board parsing - Done
Remove input mode when not SpielPrompt - Done
Remove parse error item from command input array when error happens - Done (Implemented on backend)

**Comment by alexgrejuc** [comment]
Also displaying parse errors and type errors. They work on master, but something changed and they disappeared on the master + repl merge branch I made.

**Comment by calgagi** [comment]
> Also displaying parse errors and type errors. They work on master, but something changed and they disappeared on a test branch that I made by merging master and repl.
> 
> And rejecting input that does not match the expected type.

Shouldn't rejecting input be done via a back-end response?
