### ISSUE TITLE
Continue to prompt user for input until a correctly-typed expression is given

### ISSUE THREAD

**Issue by alexgrejuc** [The-Code-In-Sheep-s-Clothing/Spiel-Front#24]
For example, in ConnectFour we have:

`type Input = Int`

However, I can do this
```
> True

true
Switched back to normal mode.
```

Additionally, it can cause this, where null is output. 

```
> let x = input(initialBoard) in x + 1

null
```

What should happen is that it should be parsed, type checked, evaluated, and then put the result in the input buffer if the type is correct. This may require some changes on the back end and in that case I can try to help.

**Comment by montymxb** [comment]
Closing as this has been implemented. The editor will continue to reprompt until an expression is able to resolve correctly.
