### ISSUE TITLE
Execute editor files directly rather than saving them

### ISSUE THREAD

**Issue by alexgrejuc** [The-Code-In-Sheep-s-Clothing/Spiel-Front#29]
We decided that due to potential vulnerabilities and overhead for managing files, space usage, and accounts, the best approach would simply be to not save files and just send program contents directly to the back end.

**Comment by calgagi** [comment]
I don't think the API supports this.

I am doing the following:
* Generating random file name (~10^17 possibilities)
* Saving code as that file name
* Running file

Not the greatest security ever, but unless the API has something that supports this, should work.

**Comment by montymxb** [comment]
Just added this in [as a PR](https://github.com/The-Code-In-Sheep-s-Clothing/Spiel-Lang/pull/81) for Spiel-Lang. Doesn't do random files though, just a single tmp_prelude.blg & tmp_tmp.blg, but I figure since these are done per request they're going to be wiped on each run.

**Comment by calgagi** [comment]
Fixed.

**Comment by montymxb** [comment]
Merged in Spiel-Lang in [PR 81](https://github.com/The-Code-In-Sheep-s-Clothing/Spiel-Lang/pull/81) :octocat:
