### ISSUE TITLE
First Command is Hidden by Topbar

### ISSUE THREAD

**Issue by montymxb** [The-Code-In-Sheep-s-Clothing/Spiel-Front#8]
After typing in a number of commands I noticed that the first thing you type eventually becomes hidden by the top bar. This doesn't happen until you type enough inputs that you have to scroll through the terminal screen. This was seen on Firefox 74.0, Mac.

<img width="567" alt="Screen Shot 2020-03-17 at 11 23 02" src="https://user-images.githubusercontent.com/5070304/76888746-afcf9000-6841-11ea-864e-396c380dbded.png">

**Comment by calgagi** [comment]
fixed in next PR
