### ISSUE TITLE
SpielTypeError needs to be Encoded as String

### ISSUE THREAD

**Issue by montymxb** [The-Code-In-Sheep-s-Clothing/Spiel-Front#9]
During our demo with Prof. Erwig I noticed the following output for a type error:
```
SpielTypeError: [object Object]
```
This just means that the associated object was printed literally. The actual data needs to be pulled out and presented as a string instead. This could be done quickly with ```JSON.stringify(obj)```, just to verify everything is there, but could be cleaned up for students & instructors to read a bit better. Overall, just a little thing.

**Comment by alexgrejuc** [comment]
Fixed
